### ISSUE TITLE
Release link

### ISSUE THREAD

**Issue by Michael21107** [Variapolis/DamageTrackerFramework#20]
add the lcpdfr.com link to the link section of about of this repo

**Comment by Variapolis** [comment]
The link is included in the Readme at the top!

**Comment by Michael21107** [comment]
@Variapolis i know, but i meant in the about section since there is a field dedicated to a URL
![image](https://github.com/Variapolis/DamageTrackerFramework/assets/121039033/5f943a9f-c5ed-41a1-9c7c-552e1da12a9a)

**Comment by Variapolis** [comment]
Will add, thanks.

**Comment by Michael21107** [comment]
yep
